

CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
DECLARE M INT;
SET M=N-1;
	RETURN (
		SELECT DISTINCT Salary FROM Employee ORDER BY Salary DESC LIMIT M, 1
	);
END

CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
SET M=N-1;
	RETURN (
		SELECT DISTINCT Salary FROM Employee ORDER BY Salary DESC LIMIT M, 1
	);
END

CREATE FUNCTION getNthHighestSalary(N INT) RETURN INT
BEGIN
	RETURN (     
		SELECT  IF(count<N,NULL,min) 
		FROM
			(SELECT MIN(Salary) AS min, COUNT(1) AS count
			FROM
				  (SELECT DISTINCT Salary
				  FROM Employee ORDER BY Salary DESC LIMIT N) AS a
			) as b
	);
END